### ISSUE TITLE
fail to add lua when compiling

### ISSUE THREAD

**Issue by lethegit** [ledisdb/ledisdb#161]
godep go install -tags 'linenoise leveldb lua' ./...
github.com/siddontang/ledisdb/vendor/lua
could not determine kind of name for C.lua_tointeger
could not determine kind of name for C.lua_tonumber
godep: go exit status 2
make: **\* [build] Error 1

An error with lua version? I 'm using lua-5.2

**Comment by siddontang** [comment]
Sorry that golua only supports lua 5.1 and I may deprecate lua feature later because it has many limitations.

**Comment by lethegit** [comment]
Thank you very much...But I have another question:how to execute a LEDIS command in Lua script ?
Is there a function like REDIS.CALL() in REDIS?Sorry to trouble you ,but I have to say the documents about LEDIS are too few....

**Comment by siddontang** [comment]
You can only `EVAL` commands, the same as Redis `EVAL`, http://redis.io/commands/eval

I don't find any good libs integrating lua in go, so this feature is just a try, I don't recommend you using it. 

Thank you.

**Comment by siddontang** [comment]
Btw, the developer for LedisDB is only me, so I don't have enough time to perfect documents. :-)

**Comment by felixbuenemann** [comment]
@siddontang I have got lua 5.2 support working in my fork ([see changes](https://github.com/siddontang/ledisdb/compare/master...felixbuenemann:lua-5.2)). If you're interested in integrating it, I could do a PR. I did not bother to keep 5.1 backwards compatibility, so my fork is 5.2 only.

**Comment by siddontang** [comment]
Thanks @felixbuenemann 

Maybe we can use building tag to distinguish 5.1, 5.2.

**Comment by felixbuenemann** [comment]
And then use two different directories, like `vendor/lua51` and `vendor/lua52`?

Maybe if the modified golua lib was in it's own package, godeps could pick up a different version, depending on which lua version is detected?

I'm no go developer, so I'm not sure if that's possible.

**Comment by siddontang** [comment]
I think we should use two folder with different building tags and let outer determine which version to use. 
Godep doesn't handle package with building tags directly.

**Comment by felixbuenemann** [comment]
OK, I'm off to be right now, but I'll give it a try tomorrow.

**Comment by siddontang** [comment]
Thanks @felixbuenemann

**Comment by unoexperto** [comment]
@felixbuenemann Have you had a chance to finish it ? I just attempted to build version with LUA 5.3 and hit same problem as you did.

**Comment by felixbuenemann** [comment]
@unoexperto Do you have a specific need for LUA 5.3? Otherwise you could just install lua 5.1 and compile against it, on mac this can be done using `brew install lua51`.

@siddontang While it's possible to use build tags and modified copies of golua with build tags to enable building against lua 5.1/5.2./5.3 (eg. lua51.go, lua52.go) it would probably be easier to just vendor a copy of the lua library. That's what redis is doing to (see [redis/deps/lua](https://github.com/antirez/redis/tree/unstable/deps/lua)).

**Comment by unoexperto** [comment]
@felixbuenemann Yes, I wanted to have bitwise operations for better implementation of base64 encoding. It was added to LUA 5.2.

**Comment by felixbuenemann** [comment]
@unoexperto I've rebased my [lua-5.2 branch](https://github.com/felixbuenemann/ledisdb/tree/lua-5.2) on top of the current master. You could try compiling it against lua 5.2.x. Compiling against lua 5.3. would likely need more changes. If you are using homebrew on a mac you should probably update the dev.sh script to point to `/usr/local/opt/lua` instead if `/usr/local/opt/lua51`.

I can't really test if it still works fine on current master, because the build environment is not working properly for me and I'm missing lots of go packages.
