### ISSUE TITLE
How to take a snapshot?

### ISSUE THREAD

**Issue by leewardbound** [ledisdb/ledisdb#176]
Hi, what is the proposed process for snapshot/backup/restore workflow? Could you please add an example to the documentation?

Right now, I see this --
/var/ledis ♟ > du -hs *
7.3G    leveldb_data
0   LOCK
4.0K    snapshot

So my main questions are --
1) How to trigger a snapshot?
2) Since I have no snapshots, can I gzip-then-rsync the leveldb_data folder offsite to effectively backup my data? (I am using in production right now, I would like to backup ASAP)
3) Would (2) fail or corrupt if my ledis sync'd to disk during the process? Is the snapshot process even needed?
4) Are the special steps to restore? Can I just copy my leveldb_data directory into the my DATA_DIR to perform a restore? Is there an import utility?

Thanks!
-Lee

**Comment by siddontang** [comment]
Hi @linked 

You can not copy and sync this folder directly.

Ledis supplies ledis-dump and ledis-load command.

You can use ledis-dump to dump the snapshot into a file, sync to other place and use ledis-load to restore.

**Comment by siddontang** [comment]
The mechanism depends on leveldb/rocksdb snapshot, so it doesn't block your service.

**Comment by nsuper** [comment]
WTH with `ledis-dump v0.5` ??? 

Version: `0.5`

1. I must delete `${datadir}/snapshot` folder

2. Stop ledis-server, because `open ledis_server/snapshot/dmp-2017-08-31T12:59:36.198949448: no such file or directory`

3. Run `ledis-dump`. OK.

4. Test add new data: `ledis-cli:6380>set abc 123`

5. Run `ledis-dump` again. Oh no, it only copy old snapshot file, not found `abc` key!!!

6. Repeat to the first step!!! Must delete `${datadir}/snapshot` folder again!!!
