### ISSUE TITLE
replication restore speed

### ISSUE THREAD

**Issue by daddyz** [ledisdb/ledisdb#277]
Currently in our setup we have about 270 million keys, local search is really fast, we have several slaves, which got replication broken. 
Trying to restore replication takes a lot of time, it starts with pretty fast writing and slows with time, it doesn't require disk and we can't see it's writing to disk during restore, which is strange, but keys do appear in db. Slowness is seen after writing 1 million rows and even before it. 
We are using goleveldb. We tried to play with goleveldb settings with no changes. 
Any advise will be appreciated.

**Comment by daddyz** [comment]
and I noticed that replication restore doesn't restore ttl of keys, at least during restore process

**Comment by siddontang** [comment]
Hi @daddyz 

It seems that goleveldb is stall, maybe you know that for the LSM DB (RocksDB, goleveldb), when the mem table is full, it will flush the mem table to level 0 SST files, but when the level 0 SST file number reaches a limit, it will slow or stop the write. I guess this is the problem here.

What's your IO until when slow begins? could you see it with `iostat` ? 

For TTL, because restore is to load raw Key-Value data into DB one by one, so it can be loaded later. 

Btw, I will try to upgrade all goleveldb, leveldb, rocksdb version, but have no time now, very sorry.
