### ISSUE TITLE
invalid zset member size

### ISSUE THREAD

**Issue by CocaCola183** [ledisdb/ledisdb#286]
看到[源码](https://github.com/siddontang/ledisdb/blob/master/ledis/const.go)里面有这个限制
```js
MaxZSetMemberSize int = 1024
```
但是假如有大于这个数据量的需求应该怎么进行调整？

**Comment by siddontang** [comment]
现在只能改源码重新编译。。。
你可以添加一个 config structure

**Comment by CocaCola183** [comment]
@siddontang 嗯，感谢抽空回复🙏  ！ 修改源码重新编译已经解决了报错问题，有几个问题还是想请教下，
* 原来1024的值是基于怎样的逻辑设定的？修改之后(1024 * 1024 * 1024)是否有可以预知的问题
* 我们的场景：
    * 高顺序写入性能
    * 不受内存限制
    * 尽可能简单的集群搭建步骤（可能的话）

基于上面的场景调研了比较多的key value数据库，最终在由leveldb驱动的一些数据库中选择了leveldb，而且很有可能会将这个投入到生产环境使用，但是团队go语言能力差，不知道您对此怎么看？

**Comment by siddontang** [comment]
rocksdb，leveldb 底层这种对于大 value 的性能堪忧，尤其是数据量大的时候，写放大特别严重，IO 顶不住的。

**Comment by CocaCola183** [comment]
@siddontang 感谢回复！不知道有没有推荐的合适的kv？

**Comment by siddontang** [comment]
如果你的需求是大 value，还不如用 kv 存 meta，你的 value 直接 append 到 file

**Comment by CocaCola183** [comment]
@siddontang 好的，再次感谢，稍后如果有有价值性能信息会在这里贴出来

**Comment by justinfx** [comment]
Sorry to comment on an old thread, but I just came across this issue while searching if another problem I had was already posted....

I have been porting an implementation using boltdb over to ledisdb and had selected a Zset as a way to support a queue of values that is ordered by an incrementing integer key. Then I just randomly saw that internally the ordered set is capped to 1024. Historically, I have seen my queue reach sizes of 8 million items, and after reading (the translation of) this ticket, it seems the Ledisdb implementation of ordered set is not suitable for this solution? Hopefully you can provide a little more insight so I can choose the right approach?

Originally I had started with the idea of:

1. Getting the next numeric id with an INCR key
1. Indexing items in a hash by id -> item
1. Managing queue order in a list of ids (referring to hash id)

After I started writing this approach, I realized that there doesn't seem to be an efficient way to remove queued items by the id without scanning the list. With boltdb, I relied upon the ability to Get(id) and also have the bucket cursor iterate the queue ordered by those ids.

Because of this, and what also seems to be the lack of transactions support the management of those multiple data structures, I thought it would be smart to switch to Zset, using the numeric incrementing id as the score. This would give me ordered queue items that could also be addressed directly by id. But I see now that there is a cap.

What is the right way to use ledisdb for this kind of item queue? Do I just need to accept the lack of transactions when maintaining secondary indices, and also accept the potential hit if Get(id) ends up scanning deep into a list that possibly has 8 million items? Zset seemed like the closest match to boltdb bucket. Unless a hash guarantees iteration is ordered by key?

**Comment by lunny** [comment]
@justinfx for an unique queue, you have to save another key copy on a set included a list.
