### ISSUE TITLE
Dose ledisdb support transaction?

### ISSUE THREAD

**Issue by FreedomMatrix2015** [ledisdb/ledisdb#305]

**Comment by siddontang** [comment]
Do, but we can re-consider it with newest RocksDB later.

**Comment by sloonz** [comment]
I see there was the beginning of an implementation of MULTI here : https://github.com/siddontang/ledisdb/commit/b2e86584701af21c23478a444ac7e32b6b908191

Why did you discarded it ?

**Comment by siddontang** [comment]
Yes, I have discarded it because the backend engine (leveldb, goleveldb) doesn't support the transaction.

RocksDB now supports it, but I have no time to re-support this feature now.

**Comment by justinfx** [comment]
Hi. I know this is an older thread but I didn't want to start a new one since there are already a few about transaction support.

It seems goleveldb supports transactions? 
https://godoc.org/github.com/syndtr/goleveldb/leveldb#Transaction

So if the 3 options left are leveldb, goleveldb, and rocksdb, is the leveldb option the only one holding back transaction support? If so, is there a real benefit to keeping leveldb if goleveldb performs just as well?
Ive just hit an issue for the second time because I forgot that the first time I tried Ledisdb I realised there were no transactions. Now I need them again :-/
Great project btw!

**Comment by siddontang** [comment]
@justinfx 

I've not known goleveldb now supporting the transaction, it is very cool, but I worry about the performance. Maybe RocksDB may still be the best choice. 

Another choice is to introduce badger which supports transaction too.

**Comment by justinfx** [comment]
@siddontang
I did have a project where I switched from Bolt to Badger and it was a decent performance boost. I feel like goleveldb is the "easy" option right now since it doesn't require any external building, and that someone choosing goleveldb would know about its strengths and weaknesses vs rocksdb. But Badger would be another easy embeddable option. However, in terms of Ram-only db, Badger doesn't have this option, and goleveldb could be adjusted to properly not require any filesystem access. 
Transaction support would be an awesome addition to this project.

**Comment by siddontang** [comment]
@justinfx 

As sad as I know, even we use memory mode for goleveldb(maybe latest version has fixed this, but I don't know), it still needs to operate files because of WAL. So now I have been searching a really pure memory implementation. :-)
