### ISSUE TITLE
Full sync replication with RocksDB is inefficient

### ISSUE THREAD

**Issue by mstory21** [ledisdb/ledisdb#339]
Is work being done to switch the full sync to use RocksDB checkpoints?  I have a 232GB database that I'm trying to sync to a slave and it's taking hours to create the snapshot.  Short of that, are there any recommendations to speed it up?

**Comment by siddontang** [comment]
hi @mstory21 

Can you tell me where the bottleneck?

1. Scanning all data from the RocksDB snapshot and writing to a file
2. Sync to the slave
3. Apply the snapshot to the slave

I guess step 3 may take a long time, is it?

**Comment by mstory21** [comment]
The main problem is 1.  It took a long time to write the dmp file out to disk and put undue stress on the box that was currently handling traffic.  Number 3 was also an issue, but it is not as concerning as 1.

**Comment by siddontang** [comment]
so the bottleneck may be the compression? if yes, maybe we should use a config to control it.

**Comment by mstory21** [comment]
I'm currently not using compression

**Comment by siddontang** [comment]
LedisDB will use snappy in full dump.

**Comment by c2h5oh** [comment]
The problem is definitely creating a db dump, which at least with RocksDB goes as follows:

1. Create a temporary rocksdb snapshot (`dmp-<timestamp>.tmp`)
2. Read temporary rocksdb snapshot and write ledisdb dump

First step is bottlenecked on read IO, specifically random read operations per second. In my case it maxes out IOPS, but read throughput remains low: 15-25% of disk sequential read speed.

a 100GB db snaphot takes about an hour to create on AWS EBS volume with 500 iops.


Second step has to read entire rocksdb snapshot and write it again in ledisdb format, which happens at disk sequential r/w speed.

Step 1 could be sped up significantly if we could use checkpoints instead of snapshots (which should be possible, but I haven't had the time to test it) or use RocksDB backup API: 

https://github.com/siddontang/ledisdb/blob/master/store/rocksdb/db.go#L238

https://github.com/facebook/rocksdb/wiki/Checkpoints

https://github.com/facebook/rocksdb/wiki/How-to-backup-RocksDB%3F

With that step 1 would be limited to creating a bunch of hardlinks on most cases without having to copy entire db. Step 2 would read the checkpoint immediately creating a ledisdb dump file or streaming it to replica.
