### ISSUE TITLE
Example using 'memory' store without filesystem access

### ISSUE THREAD

**Issue by justinfx** [ledisdb/ledisdb#362]
I'm trying to use the goleveldb "memory" `DBName` with unit tests. But it seems the process of opening any configured DB store always makes directories and files (LOCK, ...). Is this required with the in-memory store option? Is there an example of using the in-memory store without the filesystem being accessed?

```
cfg := config.NewConfigDefault()
cfg.DBName = "memory"
conn, err := ledis.Open(cfg)
// err: source temporarily unavailable
db, _ := conn.Select(0)
```

**Comment by siddontang** [comment]
Hi @justinfx 

Now memory mode uses goleveldb but it still creates WAL and some files. I will choose a pure memory implementation.

**Comment by justinfx** [comment]
Thanks for the clarification! If it doesn't need to create the files, that would be pretty cool to have a pure memory impl so I don't have to clean up temporary directories :-)

Also, thanks for this cool project.

**Comment by gq17** [comment]
Is it possible to configure big memory space(writebuffersize*Min(maxwritebuffernum, minwritebuffernumtomerge)) so that only memory is used with rocksdb?
I set following configuration and put 20G data totally, the filesystem is still used with L0 and L1

cfg.RocksDB.WriteBufferSize = 1024 * 1024 * 1024 
cfg.RocksDB.MaxWriteBufferNum = 40
cfg.RocksDB.MinWriteBufferNumberToMerge = 40

with log--------------------------------------------------
2019/11/11-18:45:14.883919 7f3e8bfff700 [/compaction_job.cc:1692] [default] Compaction start summary: Base version 26 Base level 0, inputs: [86(949MB) 84(949MB) 78(949MB) 70(949MB)], [64(1040MB) 65(1040MB) 66(1040MB) 67(1040MB) 68(1040MB) 71(1040MB) 72(1040MB) 73(1040MB) 74(1040MB) 75(1040MB) 76(1040MB) 79(1040MB) 80(1040MB) 81(1040MB) 82(586MB)]
2019/11/11-18:45:14.883936 7f3e8bfff700 EVENT_LOG_v1 {"time_micros": 1573469114883925, "job": 67, "event": "compaction_started", "compaction_reason": "LevelL0FilesNum", "files_L0": [86, 84, 78, 70], "files_L1": [64, 65, 66, 67, 68, 71, 72, 73, 74, 75, 76, 79, 80, 81, 82], "score": 1, "input_data_size": 19879658672}
